### ISSUE TITLE
Low contrast in mobile view

### ISSUE THREAD

**Issue by javigomez** [Codeception/codeception.github.com#100]
if you go to codeception.com with a narrow window (phone view) you will see that the contrast for the menu is not acessible:

![capture 2016-06-01 at 15 36 16](https://cloud.githubusercontent.com/assets/1375475/15823805/8bd65d08-2bfc-11e6-93c0-1f434bf7ba2c.png)

**Comment by DavertMik** [comment]
yes, I saw this but didn't have a chance to fix it yet. Thanks

**Comment by alanablett** [comment]
Should be fixed by #116 😄
