### ISSUE TITLE
Disqus is sending to wrong urls

### ISSUE THREAD

**Issue by javigomez** [Codeception/codeception.github.com#102]
Some of the urls at the disqus module are wrong: 

for example, if you go to:
http://codeception.com/06-03-2016/codeception-2.2-is-here.html

and click on this link
![capture 2016-06-02 at 10 06 48](https://cloud.githubusercontent.com/assets/1375475/15850329/b110fc86-2c97-11e6-803a-184022839fe4.png)

it takes to: 

http://codeception.com/06-05-2014/codeception-2.0-final.html

instead it should take to:

http://codeception.com/06-06-2014/codeception-2.0-final.html

is `06` instead of `05`

**Comment by DavertMik** [comment]
I can't manage disqus. I think we should remove it and embed our forum into the page

**Comment by Arhell** [comment]
@javigomez 
Hi, there is no Disqus in the new design.
