### ISSUE TITLE
Implement a search function for the full docs

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/codeception.github.com#137]
The search function in the docs (in the left bar, above the in-page table of contents) is basically useless, since it only duplicates what any browser offers with Ctrl+F.

What really would be useful, is a search function which searches the *entire* docs, especially across modules. Reason: In the users' minds, those modules are not separated, but all parts of the same thing (i.e. Codeception). This would allow users to discover functions which are "hidden" in modules they don't have or don't know of.

**Comment by DavertMik** [comment]
Working on this :+1:

**Comment by DavertMik** [comment]
Done
