### ISSUE TITLE
Codeception for yii: Redefine $mailer and other tips. New chapter?

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/codeception.github.com#149]
https://github.com/Codeception/codeception.github.com/blob/master/for/yii.md

is so small guide

So... I want to redefine $mailer in functional tests. I find deprecated repo with info pages
https://github.com/yiisoft/yii2-codeception/blob/master/docs/guide/usage-reconfiguring-components-for-testing.md

But this is not representation in `for/yii.md`

How about expand `for/yii.md` or try any other way to write guide? New chapter?

Additional I wish add info about redefine $mailer in functional yii2 codeception tests:

You shouldn't define the _beforeSuite inside your Cest classes. Instead, you should use the Helper class inside _support. 

in Helper
```php
    /**
     * Set \Codeception\Module\Yii2::$mailer to \Yii::$app->mailer from test
     * For example
     * public function _before(FunctionalTester $I)
     * {
     *     \Yii::$app->set('mailer', \frontend\fixtures\MockMailer::class);
     *     $I->configureMailer();
     *     $I->amOnPage(['site/contact']);
     * }
     */
    public function configureMailer()
    {
        /** @var \Codeception\Module\Yii2 $module */
        $module = $this->getModule('Yii2');
        /** @var \yii\base\Application $app */
        $app = $module->app;
        /** @var \Codeception\Lib\Connector\Yii2 $connector */
        $connector = $module->client;
        $connector::$mailer = $app->get('mailer');
    }
```

rebuild Actors;  
in `cest` use it
```php
class ContactFailCest
{
    public function _before(FunctionalTester $I)
    {
        \Yii::$app->set('mailer', \frontend\fixtures\MockMailer::class);
        $I->configureMailer();
        $I->amOnPage(['site/contact']);
    }

    public function checkContactSubmitCorrectDataSendFail(FunctionalTester $I)
    {
        $I->submitForm('#contact-form', [
            'ContactForm[name]' => 'tester',
            'ContactForm[email]' => 'tester@example.com',
            'ContactForm[subject]' => 'test subject',
            'ContactForm[body]' => 'test content',
            'ContactForm[verifyCode]' => 'testme',
        ]);
        $I->dontSeeEmailIsSent();
        $I->see(Yii::t('main', 'There was an error sending your message.'));
    }
}

```
redefine class
```php
namespace frontend\fixtures;


class MockMailer extends \Codeception\Lib\Connector\Yii2\TestMailer
{
    protected function sendMessage($message)
    {
        return false;
    }
}
```

**Comment by Naktibalda** [comment]
@samdark Please take a look at this issue.

**Comment by samdark** [comment]
Extending http://codeception.com/for/yii page sounds fine and it's liked from Yii's official guide on testing not to maintain it in two separate places.

https://github.com/yiisoft/yii2-codeception/ is deprecated altogether. Don't look into it.

**Comment by bscheshirwork** [comment]
@samdark I think we can move guide from deprecadet repo to this chapter

**Comment by samdark** [comment]
@bscheshirwork the guide in deprecated repo is not valid. It was written before Yii 2 support was moved into Codeception module.
