### ISSUE TITLE
Font(Shanti) issue on Windows

### ISSUE THREAD

**Issue by Carsak** [Codeception/codeception.github.com#150]
On windows browsers font is displayed incorrectly. Tested on latest Chrome and Firefox browser. Windows 10 x64

![image](https://user-images.githubusercontent.com/9497934/33203624-f4035442-d12a-11e7-95ac-f3345d9398dd.png)

After turn off Shanti font
![image](https://user-images.githubusercontent.com/9497934/33203667-0ec00f5a-d12b-11e7-9396-709a73e061b6.png)

**Comment by Arhell** [comment]
@Carsak 
Hi, new design fixed

**Comment by Carsak** [comment]
After two years...
Finally!
