### ISSUE TITLE
Incorrect rendering of HTML tag in Introduction documentation 

### ISSUE THREAD

**Issue by edno** [Codeception/codeception.github.com#160]
#### What are you trying to achieve?
Display the table in page [Introduction](https://codeception.com/docs/01-Introduction) in Firefox.

#### What do you get instead?
HTML tags are displayed instead of being rendered
![screenshot-codeception com-2019 03 08-20-41-22](https://user-images.githubusercontent.com/324670/54051815-fb893b80-41e2-11e9-9272-21fbc1bd9214.png)

**Comment by kirgy** [comment]
This appears to be an issue with Jekyll which is powering the markdown. A stackoverflow user reported the exact same discrepancy between rendering in Jekyll v.s. github:

https://stackoverflow.com/questions/26844701/lists-in-markdown-table-with-jekyll

The solution was to replace the markdown engine which seems a little extreme in this case. I'd say just to  use non-bullet points and separate them by new lines or something similar.

**Comment by Arhell** [comment]
@edno 
Hi, I didn’t find any problems in the new design
Thanks!
