### ISSUE TITLE
Api code coverage should say remote coverage is needed

### ISSUE THREAD

**Issue by FnTm** [Codeception/codeception.github.com#17]
I recently tried getting some code coverage from api tests, and a couple of exceptions popped up. Well, I figured out, that codeception needs the c3 file for this, even if the app is running locally to test API. 

Could this be added to the documentation? That would be very helpfull. I think it should go in http://codeception.com/docs/10-WebServices

**Comment by DavertMik** [comment]
yeah, docs should be sent into main branch
