### ISSUE TITLE
Integrate Mezzio docs

### ISSUE THREAD

**Issue by Slamdunk** [Codeception/codeception.github.com#214]
Hi, regarding the last point of https://github.com/Codeception/module-mezzio/pull/1 may someone help me indicating what would be the right pages to edit/insert/delete?

Github search is a start: https://github.com/Codeception/codeception.github.com/search?q=Expressive&unscoped_q=Expressive
But I'm a bit confused :\

**Comment by Naktibalda** [comment]
https://codeception.com/docs/modules/Mezzio
