### ISSUE TITLE
broken indent

### ISSUE THREAD

**Issue by githubeing** [Codeception/codeception.github.com#236]
i could easily fix this myself and send a pull request but i think the indents are broken for a reason and a single manual fix won't help here. maybe your automatic code formatting tool isn't properly set up or you need to format this php code as some kind of a string literal or something... - donno. but the error is there. https://github.com/Codeception/codeception.github.com/blob/0fd31fbb2248cfc32a9ff3c37abd44a2324a2dc9/quickstart.html#L106
(notice indents of lines 106-115)

**Comment by Arhell** [comment]
done

**Comment by githubeing** [comment]
are you sure _this_ is correct indenting of php code?
![Screenshot from 2020-05-06 09-08-01](https://user-images.githubusercontent.com/29702626/81142761-230b9d80-8f79-11ea-9ad8-5e0c11f36b0a.png)
afaik, e.g here is what the psr demands: https://github.com/Codeception/codeception.github.com/pull/242

**Comment by Arhell** [comment]
Thanks!
