### ISSUE TITLE
Broken link "Continue with Acceptance Tests" on Quickstart Guide

### ISSUE THREAD

**Issue by Premke** [Codeception/codeception.github.com#53]
Link "Continue with Acceptance Tests" on page [Codeception Quickstart Guide](http://codeception.com/quickstart) points to http://codeception.com/docs/04-AcceptanceTests which doesn't exist currently.

**Comment by oparoz** [comment]
MAybe create a PR with the proper link?
http://codeception.com/docs/03-AcceptanceTests

**Comment by cjaoude** [comment]
fixed.
