### ISSUE TITLE
Missing paragraphs in "Reusing Test Code"

### ISSUE THREAD

**Issue by oparoz** [Codeception/codeception.github.com#57]
The section about PageObjects is incomplete, missing important steps on how to create the UserLoginPage.
The missing bits can be found in https://github.com/Codeception/codeception.github.com/blob/97b08caed4d36c67ce91e0aff767e2a5d56518c3/docs-2.0/07-AdvancedUsage.md

**Comment by DavertMik** [comment]
Updated!
