### ISSUE TITLE
Change CSS: Remove `text-transform: uppercase;` from `<h3>`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/codeception.github.com#592]
Since I overhauled https://codeception.com/docs/reference/Configuration in https://github.com/Codeception/codeception.github.com/pull/582, the page looks ugly, as all configuration options are displayed capitalized, e.g. "ACTOR_SUFFIX".

**Comment by NaincyKumariKnoldus** [comment]
Hey @ThomasLandauer Can I do this please?

**Comment by ThomasLandauer** [comment]
Sure, but I can't merge it ;-) @TavoNiievez ?

**Comment by TavoNiievez** [comment]
I'll review and merge if you submit a PR for this.

**Comment by ThomasLandauer** [comment]
IMO, we could also remove the blue `_` in `h1:after` and `h2:after`. This looks like an anchor for permalink, but it isn't.

**Comment by NaincyKumariKnoldus** [comment]
Hello @TavoNiievez I have raised a PR now for this. Please Review this. Thanks!

**Comment by NaincyKumariKnoldus** [comment]
Done @ThomasLandauer Review it.
