### ISSUE TITLE
How to get this going locally

### ISSUE THREAD

**Issue by cjaoude** [Codeception/codeception.github.com#73]
Not exactly sure how to get this site working locally for development. I'm not seeing typical php, etc boot files. Haven't used much of static site generators, so maybe it's just that.

A quick README or CONTRIBUTING explaining this would be great. 

Tnx

**Comment by DavertMik** [comment]
It is rendered by GitHub pages, using Jekyll.
To run locally you need to install Jekyll with rubygems:

```
gem install jekyll
```

**Comment by DavertMik** [comment]
Added this to readme
