### ISSUE TITLE
Elaborate on recommendation for API to use w/ Stub/Mock creation

### ISSUE THREAD

**Issue by imme-emosol** [Codeception/codeception.github.com#826]
Where could I find more information about _why_ it is recommended to use an alternative API for creating Stubs/Mocks?
My estimation is that it has to do with compatibility with how stubs/mocks are created in PHPUnit (without Codecept).

```md
Inside unit tests (`Codeception\Test\Unit`) it is recommended to use alternative API:
```
~ [./docs/UnitTests.md](https://github.com/Codeception/codeception.github.com/blob/HEAD/docs/UnitTests.md) (HEAD, TimeOfWriting: [fc961cf1](https://github.com/Codeception/codeception.github.com/blob/fc961cf1cbffe244a6443870e5df35b5f9c7d538/docs/UnitTests.md))

**Comment by Naktibalda** [comment]
See https://github.com/Codeception/Stub/blob/4aaeffdc7089f3cae173b73bd4bc3672e4618747/src/Test/Feature/Stub.php#L42-L59 .
It verifies stub expectations after test run.

Related issues: https://github.com/Codeception/Codeception/issues/2747 https://github.com/Codeception/Codeception/issues/3005
